script: bundle exec rspec --format documentation
language: ruby
sudo: false
os:
  - linux
  - osx
osx_image: xcode12.2
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0

