script: bundle exec rspec --format documentation
language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4
matrix:
  include:
    - rvm: 2.1
      os: osx
    - rvm: 2.2
      os: osx
    - rvm: 2.3.3
      os: osx
